name: Gugusse
favicon: null
layout_spectrum: 0.28998
typography_spectrum: 0.74555
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dddddf'
    - '#b3b4c9'
    - '#6c81b0'
    - '#263bae'
    - '#8096e2'
  brandStrength: 0.6257411926053464
  lightness: 0.9754004899878055
  saturation: 0.4100802685134113
  rhythmicContrast: 0.009956400142982602
purpose: []
