name: Gugusse
favicon: null
layout_spectrum: 0.9197010565549135
typography_spectrum: 0.07207044353708625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6257411926053464
  lightness: 0.9754004899878055
  saturation: 0.4100802685134113
  rhythmicContrast: 0.009956400142982602
purpose: []
